Banner /etc/issue
ChallengeResponseAuthentication no
ClientAliveInterval 300
DisableForwarding yes
GSSAPIAuthentication no
HostbasedAuthentication no
LogLevel VERBOSE
PasswordAuthentication no
PermitEmptyPasswords no
PermitRootLogin no
PrintMotd yes
PrintLastLog yes
TCPKeepAlive no
RekeyLimit 512M 1h
KbdInteractiveAuthentication no
MaxAuthTries 2
AllowTcpForwarding no
X11Forwarding no
AllowAgentForwarding no
AuthorizedKeysFile .ssh/authorized_keyss
AllowUsers annie
