# see `man dnf.conf` for defaults and possible options

[main]
defaultyes=True
enablegroups=True
fastestmirror=True
max_parallel_downloads=10
max_downloads_per_mirror=3
keepcache=False
install_weak_deps=True
pkg_gpgcheck=True
localpkg_gpgcheck=True
