[customizations.kernel]
append = "console=tty1 console=ttyS0,115200n8"

[[customizations.user]]
name = "annie"
description = "Annie Ehler"
password = "$6$vA1r8t0lbZTB9R4b$Z3Zx.TdIv32dFQdVjyZ/P/..Mmh9x3oCTZqKD/q2fvRBP.qnrq6yQILJW9.uMcGpFynW3O9LV7vHcZTXd.dRN."
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMTijhGkE4C7yFWj0/md4R8EwLaYsyHKLTIOzJM65QHv"
home = "/var/home/annie"
shell = "/usr/bin/bash"
groups = ["users", "wheel", "virusgroup"]
uid = 1001
gid = 1001

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Runtime",
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Users",
  "org.fedoraproject.Anaconda.Modules.Timezone",
]

disable = ["org.fedoraproject.Anaconda.Modules.Subscription"]
