[DEFAULT]
db_url = sqlite:////var/lib/fangfrisch/db.sqlite
local_directory = /var/lib/clamav
cleanup = automatic
connection_timeout = 30
integrity_check = sha256

log_level = INFO
log_method = console

on_update_exec = clamdscan --reload
on_update_timeout = 30

[fangfrischnews]
enabled = yes
script = /usr/libexec/fangfrisch-has-news.sh

[interserver]
enabled = yes

[sanesecurity]
enabled = yes

[urlhaus]
enabled = yes
